### PR TITLE
Array decay in cc.Type.Params()

### PR DESCRIPTION
**Pull request by xlab**
There is a strange behaviour in `cc.Type.Params()` getter that causes array decay. Compare the signature of params from `cc.Type.String()` and `cc.Type.Params()[n].Type.String()` from the [example](https://github.com/cznic/c/blob/trunk/issues/b_array_decay_in_params/main.go).

```
issues/b_array_decay_in_params $ make
go run main.go
main.go:21: function: int(char***[2][2],char**,char[2])
main.go:24: arg char***[][2]
main.go:24: arg char**
main.go:24: arg char[]
```

The provided patch would solve the issue:

```
issues/b_array_decay_in_params $ make
go run main.go
main.go:21: function: int(char***[2][2],char**,char[2])
main.go:24: arg char***[2][2]
main.go:24: arg char**
main.go:24: arg char[2]
```

But I think this has been done for a reason.

### CODE REVIEW

**Comment by cznic** [comment]
@xlab I cannot use the PR because merging it fails tests. Instead I've created branch `pr2` that incorporates your PR and fix the tests. Please review [the change](https://github.com/cznic/c/commit/99abc211762dfbcf6bb3c2d9d15b7b200d56117b), thank you.

**Comment by cznic** [comment]
@xlab I'm sure you're busy with other tasks, so I'll going to break the rules and merge the change for the sake of making progress faster. We can revert any time later if you'll find any problem with this, okay?

**Comment by cznic** [comment]
Closing via https://github.com/cznic/c/commit/99abc211762dfbcf6bb3c2d9d15b7b200d56117b

**Comment by xlab** [comment]
> for the sake of making progress faster. We can revert any time later if you'll find any problem with this, okay?

Sure, feel free to save time on this, it's your project anyways. In cases when additional problems will arise, I think that should be just another issue.

**Pull request closed without merging**
